logging:
  level:
    liquibase: INFO
spring:
  application:
    name: orders
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  cloud:
    stream:
      rabbit:
        bindings:
          rtmsOrdersIn:
            consumer:
              autoBindDlq: true
      bindings:
        rtmsOrdersOut:
          contentType: 'application/*+avro'
          group: rtms
        rtmsOrdersIn:
          destination: rtmsOrdersIn
          group: rtms
