spring:
  cloud:
    stream:
      rabbit:
        bindings:
          input:
            consumer:
              autoBindDlq: true
      bindings:
        output:
          contentType: 'application/*+avro'
          group: rtms
        input:
          destination: input
          group: rtms
