spring:
  application:
    name: orders
  cloud:
    stream:
      rabbit:
        bindings:
          rtmsOrdersIn:
            consumer:
              autoBindDlq: true
      bindings:
        rtmsOrdersOut:
          contentType: 'application/*+avro'
          group: rtms
        rtmsOrdersIn:
          destination: rtmsOrdersIn
          group: rtms
